```yaml
# General settings
general:
  db_path: data/news.db
  log_level: INFO

# Scraper settings
scraper:
  enabled_spiders:
    - hacker_news
    - the_verge_tech
    - a_astral_codex
    - cna_all
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'

# Processor settings
processor:
  model_name: "facebook/bart-large-cnn"
  max_length: 150
  min_length: 50

# Recommender settings
recommender:
  # =========================================================
  # !! 在这里配置你真正感兴趣的关键词 !!
  # !! 我已经根据你之前的需求为你填写好了 !!
  # =========================================================
  keywords:
    # --- GitHub 有趣的开源项目 ---
    - 'GitHub Trending'
    - 'Open Source Project'
    - 'Awesome List'
    - '开源项目'

    # --- AI 智能体 ---
    - 'AI Agent'
    - '智能体'
    - 'AutoGPT'
    - 'LangChain'

    # --- 开发 & Linux & DigitalOcean ---
    - 'Linux Kernel'
    - 'Docker and Kubernetes'
    - 'DevOps'
    - 'DigitalOcean'
    - 'Python'
    - 'Golang'
    - 'Rust'

    # --- 国内外热点新闻 ---
    - 'Tech industry news'
    - '科技行业动态'
    - 'Startup funding'
  
  # 相似度阈值，0.4 是一个很好的起点
  similarity_threshold: 0.4

# Notifier settings (在 Actions 模式下此部分会被忽略，但保留结构)
notifier:
  provider: wework
  bark_url: ''
  pushdeer_key: ''
  wework_webhook_url: ''

# Scheduler settings (在 Actions 模式下此部分会被忽略)
scheduler:
  job_interval_hours: 4
```
